# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-05-03 05:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_auto_20180503_1141'),
        ('document', '0021_auto_20180410_1522'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='document_authors_name_in_other_language',
            field=models.ManyToManyField(blank=True, related_name='authors_in_other_language', to='core.Biography', verbose_name='Author(s) Name in other language'),
        ),
    ]
