# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-05-03 07:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0022_document_document_authors_name_in_other_language'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='document_authors_name_in_other_language',
        ),
    ]
