# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-05-09 10:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0023_remove_document_document_authors_name_in_other_language'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='documentfileupload',
            options={'ordering': ['created_date']},
        ),
        migrations.AlterModelOptions(
            name='documentlinkinfo',
            options={'ordering': ['created_date']},
        ),
    ]
