# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-05-10 10:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0026_auto_20180510_1601'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentfileupload',
            name='total_pages',
            field=models.IntegerField(editable=False),
        ),
    ]
