# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-04-10 09:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0016_auto_20180406_1547'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='license',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.LicenseType', verbose_name='license'),
        ),
        migrations.AlterField(
            model_name='videolinkinfo',
            name='link_description',
            field=models.TextField(blank=True, max_length=500, verbose_name='Link Description'),
        ),
        migrations.AlterField(
            model_name='videolinkinfo',
            name='link_name',
            field=models.URLField(max_length=500, verbose_name='Link URL'),
        ),
    ]
