# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-05-09 09:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_auto_20180509_1155'),
        ('video', '0020_auto_20180509_1155'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='video_director',
        ),
        migrations.AddField(
            model_name='video',
            name='video_director',
            field=models.ManyToManyField(blank=True, related_name='directors', to='core.Biography', verbose_name='Director'),
        ),
    ]
