# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-05-10 10:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0022_auto_20180510_1559'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='publication_year_on_text',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Publication year'),
        ),
        migrations.AlterField(
            model_name='video',
            name='year_of_available_on_text',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Year of available'),
        ),
    ]
