# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-05-10 10:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0023_auto_20180510_1601'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='video_release_date',
            field=models.CharField(blank=True, max_length=255, verbose_name='Release date'),
        ),
        migrations.AlterField(
            model_name='video',
            name='video_running_time',
            field=models.CharField(blank=True, max_length=255, verbose_name='Running time in minutes'),
        ),
    ]
