# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-04-06 10:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_auto_20180320_1424'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sponsor',
            name='description',
            field=models.TextField(blank=True, verbose_name='Description'),
        ),
    ]
