# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-05-03 05:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_genre_audio_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genre_audio_video',
            name='custom_genre',
            field=models.CharField(max_length=255, unique=True, verbose_name='genre name'),
        ),
        migrations.AlterField(
            model_name='genre_audio_video',
            name='genre_description',
            field=models.TextField(blank=True, default='', verbose_name='genre description'),
        ),
    ]
