# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-05-07 09:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_biography_authors_name_in_other_language'),
    ]

    operations = [
        migrations.AddField(
            model_name='biography',
            name='place_of_birth',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Place of birth'),
        ),
    ]
