# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-05-07 11:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_biography_place_of_birth'),
    ]

    operations = [
        migrations.AlterField(
            model_name='educationlevel',
            name='level',
            field=models.CharField(max_length=255, unique=True, verbose_name='Education Level'),
        ),
        migrations.AlterField(
            model_name='licensetype',
            name='license',
            field=models.CharField(max_length=50, null=True, verbose_name='License'),
        ),
    ]
