# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-05-09 06:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_auto_20180507_1717'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='biography',
            name='genre',
        ),
        migrations.AddField(
            model_name='biography',
            name='genre',
            field=models.ManyToManyField(blank=True, to='core.genre_audio_video', verbose_name='Genre'),
        ),
    ]
