# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-05-10 10:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_auto_20180509_1155'),
    ]

    operations = [
        migrations.AlterField(
            model_name='biography',
            name='dob',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Date of birth'),
        ),
        migrations.AlterField(
            model_name='biography',
            name='name',
            field=models.CharField(default='', max_length=255, verbose_name='Name'),
        ),
    ]
