# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-05-14 10:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_auto_20180510_1608'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='keyword',
            options={'ordering': ['created_date']},
        ),
    ]
