# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-04-03 09:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0003_auto_20180307_1423'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collection',
            name='community_name',
            field=models.CharField(choices=[('literatures and arts', 'Literature and arts'), ('course materials', 'Course materials'), ('teaching materials', 'Teaching materials'), ('reference materials', 'Reference materials'), ('newpapers and magazines ', 'Newpapers and magazines'), ('other educational materials', 'Other educational materials')], max_length=255, verbose_name='Community'),
        ),
    ]
