# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-04-13 09:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_auto_20180410_1522'),
        ('audio', '0017_auto_20180410_1522'),
    ]

    operations = [
        migrations.AddField(
            model_name='audio',
            name='audio_original_document_authors',
            field=models.ManyToManyField(blank=True, related_name='audio_original_document_authors', to='core.Biography', verbose_name='Author(s)'),
        ),
        migrations.AddField(
            model_name='audio',
            name='audio_release_date',
            field=models.CharField(blank=True, max_length=25, verbose_name='Release date'),
        ),
    ]
