# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-05-09 06:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_auto_20180509_1155'),
        ('audio', '0020_auto_20180509_1155'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='audio',
            name='audio_read_by',
        ),
        migrations.AddField(
            model_name='audio',
            name='audio_read_by',
            field=models.ManyToManyField(blank=True, to='core.Biography', verbose_name='Read / Voice by'),
        ),
    ]
